export type UserProfileDto = {
  id: string;
  email: string;
  username: string;
  firstName: string;
  lastName: string;
  role: string;
  avatarUrl?: string | null;
  headline?: string | null;
  bio?: string | null;
  targetRole?: string | null;
  location?: string | null;
  phoneNumber?: string | null;
  showEmail?: boolean;
  currentCompany?: string | null;
  currentPosition?: string | null;
  yearsExperience?: number | null;
  education?: unknown;
  profileSkills?: unknown;
  profileCertifications?: unknown;
  profileProjects?: unknown;
  preferredJobType?: string | null;
  preferredWorkMode?: string | null;
  preferredSalaryRange?: string | null;
  languages?: unknown;
  experienceSummary?: string | null;
  mentorSpecialties?: unknown;
  mentorExpertise?: unknown;
  mentorRating?: number | null;
  mentorCompletedReviews?: number;
  socialLinks?: Record<string, string> | null;
  isPublicProfile?: boolean;
  createdAt: Date;
};

export type UpdateUserProfilePayload = {
  username?: string;
  firstName?: string;
  lastName?: string;
  avatarUrl?: string | null;
  headline?: string | null;
  bio?: string | null;
  targetRole?: string | null;
  location?: string | null;
  phoneNumber?: string | null;
  showEmail?: boolean;
  currentCompany?: string | null;
  currentPosition?: string | null;
  yearsExperience?: number | null;
  education?: unknown;
  profileSkills?: unknown;
  profileCertifications?: unknown;
  profileProjects?: unknown;
  preferredJobType?: string | null;
  preferredWorkMode?: string | null;
  preferredSalaryRange?: string | null;
  languages?: unknown;
  experienceSummary?: string | null;
  mentorSpecialties?: unknown;
  mentorExpertise?: unknown;
  socialLinks?: Record<string, string> | null;
  isPublicProfile?: boolean;
};
