ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'INTERVIEW_REMINDER';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ROADMAP_REMINDER';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'JOB_MATCH';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CAREER_GOAL';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'INTERVIEW_FEEDBACK';

ALTER TABLE "notifications" ADD COLUMN IF NOT EXISTS "actionLink" TEXT;
ALTER TABLE "notifications" ADD COLUMN IF NOT EXISTS "dedupeKey" TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS "notifications_userId_dedupeKey_key"
ON "notifications"("userId", "dedupeKey");
