ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "bio" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "targetRole" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "phoneNumber" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "showEmail" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "currentCompany" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "currentPosition" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "yearsExperience" INTEGER;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "education" JSONB;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "profileSkills" JSONB;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "profileCertifications" JSONB;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "profileProjects" JSONB;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "preferredJobType" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "preferredWorkMode" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "preferredSalaryRange" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "languages" JSONB;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "experienceSummary" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "socialLinks" JSONB;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "isPublicProfile" BOOLEAN NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS "users_isPublicProfile_idx"
ON "users"("isPublicProfile");
